#!/bin/bash

LOG_FILE="./results.log"
TEST_STR="///////////////////////////////"
TTY="/dev/ttyUSB0"


err() {
    echo -e "\t$1" | tee -a "$LOG_FILE"
    echo "----------------------------" | tee -a "$LOG_FILE"

    rm $tmp_f
    exit 1
}

power_supply() {
    expect -i >> /dev/null <<EOF
        spawn cat "$TTY"
    
        # time to connect power cable
        set timeout 10
        expect {
            "U-Boot SPL" { puts "\n$TEST_STR DEVICE CONNECTED $TEST_STR\n" }
            timeout { puts "TIME OUT\n"; close; exit 3 }
        }

        close
EOF

    if [ "$?" -ne "0" ]; then
        err "power was not supplied"
    else
        echo -e "\tpower supplied" | tee -a "$LOG_FILE"
    fi
}

write_info() {
    expect -i >> /dev/null <<EOF
        log_file $tmp_f
        spawn cat "$TTY"
    
        # time to connect power cable
        set timeout 20
        expect {
            "Hit any key to stop autoboot:" { puts "\n$TEST_STR END OF RECORD $TEST_STR\n" }
            timeout { puts "TIME OUT\n"; close; exit 3 }
        }

        close
EOF
}

check_optee_info() {
    result="$(cat $tmp_f | grep 'I/TC:' | tail -n 4)"

    if [ -z "$(echo $result | grep 'OP-TEE version:')" ] || [ -z "$(echo $result | grep 'Successfully captured Cyres certificate chain')" ] || [ -z "$(echo $result | grep 'Successfully captured Cyres private key')" ] || [ -z "$(echo $result | grep 'Initialized')" ]; then
        err "test failed"
    fi
    echo -e "\tOP-TEE work done" | tee -a $LOG_FILE
    echo "$result"
    
}


####################
# start of execution
####################
clear
stty min 1 time 0 line 0 -brkint -icrnl -imaxbel -opost -isig -icanon -iexten -echo clocal cread cs8 -cstopb -parenb -F $TTY speed 115200
echo "----------------------------" | tee -a "$LOG_FILE"
echo "start checking OPTEE" | tee -a "$LOG_FILE"
echo "pls insert the power cable into trustboard(10s)"

power_supply
tmp_f=`mktemp /tmp/OPTEE_test_data.XXXXX`
write_info
check_optee_info
rm $tmp_f

echo
echo "test done" | tee -a $LOG_FILE
echo "----------------------------" | tee -a $LOG_FILE
