#!/bin/bash

LOG_FILE="./results.log"
PROMPT="=>"
TEST_STR="///////////////////////////////"
TTY="/dev/ttyUSB0"


err() {
    echo -e "\t$1" | tee -a "$LOG_FILE"
    echo "----------------------------" | tee -a "$LOG_FILE"

    kill -9 `head -n 1 $tmp_f`
    rm $tmp_f
    exit 1
}

test_bootloader() {
    expect -i >> /dev/null <<EOF
        spawn cat "$TTY"
    
        # time to connect power cable
        set timeout 10
        expect {
            "U-Boot SPL" { puts "\n$TEST_STR DEVICE CONNECTED $TEST_STR\n" }
            timeout { puts "TIME OUT\n"; close; exit 3 }
        }
    
        # time to finish bootloader(u-boot) work
        set timeout 7
        expect {
            "Hit any key to stop autoboot:" { puts "\n$TEST_STR U-BOOT PROMPT $TEST_STR\n" }
            timeout { puts "TIME OUT\n"; close; exit 4 }
        }

        close
EOF

    res="$?"
    if [ "$res" -ne "0" ]; then
        if [ "$res" -eq "3" ]; then
            echo -e "\tpower was not supplied" | tee -a "$LOG_FILE"
        elif [ "$res" -eq "4" ]; then
            echo -e "\tU-boot not work" | tee -a "$LOG_FILE"
        fi
        err
    else
        echo > "$TTY"
        if [ "$1" == "-verbose" ]; then
            echo -e "\tpower supplied. U-boot prompt:" | tee -a "$LOG_FILE"  
        fi
    fi
}

pfe_stop() {
    awk 'BEGIN {
            system("cat '$TTY' & echo $!")
        }' > $tmp_f
    sleep 1

    echo "pfe stop" > $TTY
    sleep 1
    res="$(cat $tmp_f | grep --color=never -A 2 "pfe stop" | tail -n 2)"
    echo "/////pfe-stop result : '$res'"

    if [[ `echo $res | tail -n 1` == *$PROMPT* ]] && [[ `echo $res | head -n 1` == *Stopping* ]]; then
        echo -e "\tPFE successful stop" | tee -a "$LOG_FILE"
    else
        err "pfe stop error"
    fi

    kill -9 `head -n 1 $tmp_f`
}


####################
# start of execution
####################
clear
parse_options $@
stty min 1 time 0 line 0 -brkint -icrnl -imaxbel -opost -isig -icanon -iexten -echo clocal cread cs8 -cstopb -parenb -F $TTY speed 115200
echo "----------------------------" | tee -a "$LOG_FILE"
echo "start pfe-stop test" | tee -a "$LOG_FILE"
echo "pls insert the power cable into trustboard(10s)"

tmp_f=`mktemp /tmp/data.XXXXX`
test_bootloader -verbose
pfe_stop
rm $tmp_f

echo -e "test done" | tee -a "$LOG_FILE"
echo "----------------------------" | tee -a "$LOG_FILE"
