#!/bin/bash

TEST_LIST="./test_list.txt"
LOG_FILE="./results.log"

test_list=`cat $TEST_LIST`

while IFS= read -r it; do
    echo "it = $it"
    sleep 1
    if [ -f "./${it%% *}" ]; then
        echo "start test : ${it%% *}" # >> "$LOG_FILE"
        #bash $it
        echo "bash $it" # >> "$LOG_FILE"
    fi
    echo # >> "$LOG_FILE"
done < "$TEST_LIST"
