#!/bin/bash

LOG_FILE="./results.log"
TEST_STR="///////////////////////////////"
TTY="/dev/ttyUSB0"
Model="Trustbox"
Board="Trustbox"

err() {
    echo -e "\t$1" | tee -a "$LOG_FILE"
    echo "----------------------------" | tee -a "$LOG_FILE"

    rm $tmp_f
    exit 1
}

power_supply() {
    expect -i >> /dev/null <<EOF
        spawn cat "$TTY"
    
        # time to connect power cable
        set timeout 10
        expect {
            "U-Boot SPL" { puts "\n$TEST_STR DEVICE CONNECTED $TEST_STR\n" }
            timeout { puts "TIME OUT\n"; close; exit 3 }
        }

        close
EOF

    if [ "$?" -ne "0" ]; then
        err "power was not supplied"
    else
        echo -e "\tpower supplied" | tee -a "$LOG_FILE"
    fi
}

write_info() {
    expect -i >> /dev/null <<EOF
        log_file $tmp_f
        spawn cat "$TTY"
    
        # time to connect power cable
        set timeout 20
        expect {
            "Hit any key to stop autoboot:" { puts "\n$TEST_STR END OF RECORD $TEST_STR\n" }
            timeout { puts "TIME OUT\n"; close; exit 3 }
        }

        close
EOF
}

check_model() {
    result="$(cat $tmp_f | grep -A 1 'Model:')"

    if [ -z "$(echo $result | head -n 1 | grep $Model)" ]; then
        err "test failed"
    fi
    if [ -z "$(echo $result | tail -n 1 | grep $Board)" ]; then
        err "test failed"
    fi
    
    echo -e "\tModel and Board found" | tee -a $LOG_FILE
    echo "$result"   
}


####################
# start of execution
####################
clear
stty min 1 time 0 line 0 -brkint -icrnl -imaxbel -opost -isig -icanon -iexten -echo clocal cread cs8 -cstopb -parenb -F $TTY speed 115200
echo "----------------------------" | tee -a "$LOG_FILE"
echo "start checking model" | tee -a "$LOG_FILE"
echo "pls insert the power cable into trustboard(10s)"

tmp_f=`mktemp /tmp/OPTEE_test_data.XXXXX`
power_supply
write_info
check_model
rm $tmp_f

echo
echo "test done" | tee -a $LOG_FILE
echo "----------------------------" | tee -a $LOG_FILE
